export type Prefecture = {
  order: number;
};
export const prefectures = (): Record<string, Prefecture> => {
  return {
    北海道: { order: 1 },
    青森県: { order: 2 },
    岩手県: { order: 3 },
    宮城県: { order: 4 },
    秋田県: { order: 5 },
    山形県: { order: 6 },
    福島県: { order: 7 },
    茨城県: { order: 8 },
    栃木県: { order: 9 },
    群馬県: { order: 10 },
    埼玉県: { order: 11 },
    千葉県: { order: 12 },
    東京都: { order: 13 },
    神奈川県: { order: 14 },
    新潟県: { order: 15 },
    富山県: { order: 16 },
    石川県: { order: 17 },
    福井県: { order: 18 },
    山梨県: { order: 19 },
    長野県: { order: 20 },
    岐阜県: { order: 21 },
    静岡県: { order: 22 },
    愛知県: { order: 23 },
    三重県: { order: 24 },
    滋賀県: { order: 25 },
    京都府: { order: 26 },
    大阪府: { order: 27 },
    兵庫県: { order: 28 },
    奈良県: { order: 29 },
    和歌山県: { order: 30 },
    鳥取県: { order: 31 },
    島根県: { order: 32 },
    岡山県: { order: 33 },
    広島県: { order: 34 },
    山口県: { order: 35 },
    徳島県: { order: 36 },
    香川県: { order: 37 },
    愛媛県: { order: 38 },
    高知県: { order: 39 },
    福岡県: { order: 40 },
    佐賀県: { order: 41 },
    長崎県: { order: 42 },
    熊本県: { order: 43 },
    大分県: { order: 44 },
    宮崎県: { order: 45 },
    鹿児島県: { order: 46 },
    沖縄県: { order: 47 },
  };
};
