tabWidth: 2
useTabs: false
singleQuote: false
trailingComma: "es5"
semi: true
importOrder:
  - "<BUILTIN_MODULES>"
  - "<THIRD_PARTY_MODULES>"
  - ""
  - "^[.]"
plugins:
  - "@ianvs/prettier-plugin-sort-imports"
